FROM python:3.11.4

WORKDIR /wd

RUN apt update && apt upgrade -y

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip && \
    pip install --requirement requirements.txt

COPY ./app app
COPY ./tests tests

CMD ["pytest", "./tests/test_main.py"]